"""adding position tracking for units and lessons

Revision ID: 0c82a3cacb88
Revises: d5b9dd676301
Create Date: 2022-02-15 16:33:31.250617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c82a3cacb88'
down_revision = 'd5b9dd676301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('unit', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'position')
    op.drop_column('lesson', 'position')
    # ### end Alembic commands ###
