"""adding soft-delete to page

Revision ID: 1a506405de4f
Revises: fcb5f6ab9069
Create Date: 2022-06-10 10:55:38.050250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a506405de4f'
down_revision = 'fcb5f6ab9069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'active')
    # ### end Alembic commands ###
