"""adding question data

Revision ID: 303762aa4925
Revises: ed8dd1b47418
Create Date: 2022-02-07 12:43:20.779258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303762aa4925'
down_revision = 'ed8dd1b47418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INLINE_TEXT', 'INLINE_DROPDOWN', 'PARAGRAPH', 'CHOICE', name='questiontype'), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option')
    op.drop_table('question')
    # ### end Alembic commands ###
