"""add email to user

Revision ID: 681bc958b59d
Revises: 75c22c57f334
Create Date: 2022-05-17 15:13:23.794320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681bc958b59d'
down_revision = '75c22c57f334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
