"""name for class

Revision ID: 743e44f5b0b1
Revises: 8d7458f5e4b0
Create Date: 2022-02-10 09:21:53.394812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743e44f5b0b1'
down_revision = '8d7458f5e4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class', 'name')
    # ### end Alembic commands ###
