"""linking users to schools

Revision ID: 776c627b35ab
Revises: e0c08406db78
Create Date: 2022-05-17 16:43:48.258257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776c627b35ab'
down_revision = 'e0c08406db78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_user')
    # ### end Alembic commands ###
