"""setting flag for locking answers

Revision ID: bed827639ace
Revises: 78564072f911
Create Date: 2022-05-05 15:51:21.980228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed827639ace'
down_revision = '78564072f911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('locked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'locked')
    # ### end Alembic commands ###
