"""rubric item points

Revision ID: cb7f7f84b88b
Revises: a2cd529b8c19
Create Date: 2022-03-25 03:54:30.238342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7f7f84b88b'
down_revision = 'a2cd529b8c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rubric_item', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rubric_item', 'points')
    # ### end Alembic commands ###
