"""setting flag for submitting answers

Revision ID: d287e378eca6
Revises: bed827639ace
Create Date: 2022-05-10 16:28:25.540599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd287e378eca6'
down_revision = 'bed827639ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('submitted', sa.Boolean(), nullable=True))
    op.alter_column('answer', 'locked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'locked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('answer', 'submitted')
    # ### end Alembic commands ###
