"""allow units to be hidden

Revision ID: fcb5f6ab9069
Revises: 7f4d43aea863
Create Date: 2022-05-25 10:21:46.455737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb5f6ab9069'
down_revision = '7f4d43aea863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'published')
    # ### end Alembic commands ###
